### ISSUE TITLE
В целом

### ISSUE THREAD

**Issue by ustasby** [cia1/plushka-cms#1]
Увидел хвалебный отзыв, и скажу по существу - в топку такой код.

**Comment by cia1** [comment]
Если это не будет слишком обременительным, то прошу написать что конкретно плохо. Если ваши доводы окажутся убедительными, обещаю исправить.

**Comment by ustasby** [comment]
Просто все, начиная с первой строки! Но если ты хочешь подробностей, то запости тему на пхпклубе, подробно все разжуют, почуствуешь себя говном и встанешь на путь исправления!

**Comment by cia1** [comment]
Такого не бывает, чтобы всё. Поэтому сочту вашу критику лишь личным субъективным мнением.
